export const GET_CHARACTERS = "GET_CHARACTERS";
export const DETALLE_PERSONAJE = "DETALLE_PERSONAJE";
export const LIMPIAR_DETALLE = "LIMPIAR_DETALLE";
export const LIMPIAR_PERSONAJES = "LIMPIAR_PERSONAJES";
